sudo: required
language: cpp
services:
- docker
env:
- DOVECOT="master-2.3"
before_install:
- docker network create --driver=bridge --subnet=192.168.100.0/24 --gateway=192.168.100.1 ceph_network
- travis_wait 30 docker run -itd --name build --net=ceph_network -e SOURCE_VERSION=$DOVECOT -v $(pwd):/repo cephdovecot/travis-build:$DOVECOT sh
- docker exec build apt-get -qq update
- docker exec build apt-get -qq upgrade
- docker exec build sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -qq -q libcurl4-openssl-dev'
before_script:
- docker exec build sh -c 'cd /usr/local/src/dovecot; git pull origin $SOURCE_VERSION'
- docker exec build sh -c 'cd /usr/local/src/dovecot; make install'
script:
- docker exec build sh -c 'cd repo; ./autogen.sh'
- docker exec build sh -c 'cd repo; ./configure --with-dovecot=/usr/local/lib/dovecot'
- docker exec build sh -c 'cd repo; make clean all'

after_script:
- docker network rm ceph_network

